{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.liushichao.gradles",
    "module": "plugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cwenmw4ycnfrpbb4rvjhy5eu34"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ament-0.0.1.jar",
          "url": "ament-0.0.1.jar",
          "size": 75157,
          "sha512": "481f69cda7ae7fdff916b1d14c9bbbb93103b7c5b9d28611a107bf3d2ddb565411c2baef88970bbc8558a5fd24564ca037620e8fbc01897ba8690df59a3e0117",
          "sha256": "910b8e9fe8172f534932cb3bdd68f930cfae905d44c024d739ea6cd6a1e3f1ae",
          "sha1": "b179d5be6f1ff3db8fa2b29c190bab6357bcce41",
          "md5": "a7ff471e098f55c3d30eb7a787bd4eee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "ament-0.0.1.jar",
          "url": "ament-0.0.1.jar",
          "size": 75157,
          "sha512": "481f69cda7ae7fdff916b1d14c9bbbb93103b7c5b9d28611a107bf3d2ddb565411c2baef88970bbc8558a5fd24564ca037620e8fbc01897ba8690df59a3e0117",
          "sha256": "910b8e9fe8172f534932cb3bdd68f930cfae905d44c024d739ea6cd6a1e3f1ae",
          "sha1": "b179d5be6f1ff3db8fa2b29c190bab6357bcce41",
          "md5": "a7ff471e098f55c3d30eb7a787bd4eee"
        }
      ]
    }
  ]
}
