{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.liushichao.gradles",
    "module": "plugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "p5p64qhdpzel7gbcbrrdcrmrnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ament-0.0.1.jar",
          "url": "ament-0.0.1.jar",
          "size": 74884,
          "sha512": "2549bd4af57b5a0685322c297cf80c6cf781e9b9fc7a8bc4ef99a878c8c2ef241e1da1fb514dae139cc3b2ab9ed4f1902ac5ebae768a488dd1914ec1af372da1",
          "sha256": "5127abdb17ed481294cefc9047a15e90989361eb7bc249b77bb173f92838d741",
          "sha1": "c01086de8cfe9d1f114d10f41d070dcc1c417518",
          "md5": "e65e6de121be2bf6e2246ac747f50d71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "ament-0.0.1.jar",
          "url": "ament-0.0.1.jar",
          "size": 74884,
          "sha512": "2549bd4af57b5a0685322c297cf80c6cf781e9b9fc7a8bc4ef99a878c8c2ef241e1da1fb514dae139cc3b2ab9ed4f1902ac5ebae768a488dd1914ec1af372da1",
          "sha256": "5127abdb17ed481294cefc9047a15e90989361eb7bc249b77bb173f92838d741",
          "sha1": "c01086de8cfe9d1f114d10f41d070dcc1c417518",
          "md5": "e65e6de121be2bf6e2246ac747f50d71"
        }
      ]
    }
  ]
}
